import Header from "@/components/Header";
import Main from "@/components/Main";
import Overlay from "@/components/Overlay";
import Head from "next/head";
import { useState } from "react";
import { AnimatePresence } from "framer-motion";

export default function Home() {
  const [openModal, setOpenModal] = useState(false);
  return (
    <div>
      <Head>
        <title>Mirfayz Karimov</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link as="icon" rel="icon" href="/me.png" />
      </Head>

      <Header />
      <Main setOpenModal={setOpenModal} />
      <AnimatePresence>
        {openModal && <Overlay close={() => setOpenModal(false)} />}
      </AnimatePresence>
    </div>
  );
}
