import Header from "@/components/Header";
import Main from "@/components/Main";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mirfayz Karimov</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link as="icon" rel="icon" href="/me.png" />
      </Head>

      <Header />
      <Main />
    </div>
  );
}
